[tox]
isolated_build = true
envlist = py{312, 311, 310}-pytest{latest},lint

[testenv]
allowlist_externals = pdm
commands =
    pdm install -G examples -G tests
    pytest

[testenv:lint]
description = lint source code
deps =
    ruff
commands =
    ruff check
    ruff format --check
