config:
  project_repos:
    myrepo:
      repo: 'https://github.com/IraitzM/data-complexity-profiler'

sqa_criteria:
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker nosetests:
        commands:
        - /usr/bin/env sh .sqa/script.nosetests.sh
        container: qc.unit_udocker

timeout: 1800