name: Quality assurance

on:
  push:
    branches:
      - main

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

        # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: pdm install

      - name: Check coverage
        run: pdm run coverage run -m pytest

      - uses: eosc-synergy/sqaaas-assessment-action@v2

      - name: Build package
        run: pdm build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
